services:
  - type: web
    name: rouchelle-scooter-theorie
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: true
